org: facubazzi
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  logs:
    httpApi: true
  httpApi:
    authorizers:
      customAuthorizer:
        type: request
        functionName: auth
        enableSimpleResponses: true

functions:
  auth:
    handler: src/auth.handler
  getAll:
    handler: src/getAll.handler
    events:
      - httpApi:
          path: /
          method: get
  getById:
    handler: src/getById.handler
    events:
      - httpApi:
          path: /{id}
          method: get
  post:
    handler: src/post.handler
    events:
      - httpApi:
          path: /
          method: post
          authorizer:
            name: customAuthorizer
  patch:
    handler: src/patch.handler
    events:
      - httpApi:
          path: /
          method: patch

package:
  patterns:
    - src/database.json

plugins:
  - serverless-offline
