org: facubazzi
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  getAll:
    handler: src/getAll.handler
    events:
      - httpApi:
          path: /
          method: get
  getById:
    handler: src/getById.handler
    events:
      - httpApi:
          path: /{id}
          method: get
  post:
    handler: src/post.handler
    events:
      - httpApi:
          path: /
          method: post
  patch:
    handler: src/patch.handler
    events:
      - httpApi:
          path: /
          method: patch